#############################################################################
# Makefile for building: kaiwu
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  kaiwu.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 CONFIG+=debug -o Makefile kaiwu.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
SUBTARGETS    =  \
		sub-kaiwu \
		sub-test


sub-kaiwu-qmake_all:  FORCE
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile
	cd kaiwu/ && $(MAKE) -f Makefile qmake_all
sub-kaiwu: FORCE
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-kaiwu-make_first: FORCE
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-kaiwu-all: FORCE
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-kaiwu-clean: FORCE
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-kaiwu-distclean: FORCE
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-kaiwu-install_subtargets: FORCE
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-kaiwu-uninstall_subtargets: FORCE
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-test-qmake_all:  FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile
	cd test/ && $(MAKE) -f Makefile qmake_all
sub-test: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-test-make_first: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-test-all: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-test-clean: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-test-distclean: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-test-install_subtargets: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-test-uninstall_subtargets: FORCE
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: kaiwu.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		kaiwu.pro
	$(QMAKE) -spec linux-g++-64 CONFIG+=debug -o Makefile kaiwu.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
kaiwu.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 CONFIG+=debug -o Makefile kaiwu.pro

qmake_all: sub-kaiwu-qmake_all sub-test-qmake_all FORCE

make_first: sub-kaiwu-make_first sub-test-make_first FORCE
all: sub-kaiwu-all sub-test-all FORCE
clean: sub-kaiwu-clean sub-test-clean FORCE
distclean: sub-kaiwu-distclean sub-test-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-kaiwu-install_subtargets sub-test-install_subtargets FORCE
uninstall_subtargets: sub-kaiwu-uninstall_subtargets sub-test-uninstall_subtargets FORCE

sub-kaiwu-check:
	@test -d kaiwu/ || mkdir -p kaiwu/
	cd kaiwu/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/kaiwu/kaiwu.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-test-check:
	@test -d test/ || mkdir -p test/
	cd test/ && ( test -e Makefile || $(QMAKE) /media/psf/Home/Developer/kaiwu/test/test.pro -spec linux-g++-64 CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-kaiwu-check sub-test-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

